import glob
import os
from pathlib import Path
from secondary_analysis import SecondaryAnalysis

fastqs_path = config['fastqs_path']
analysis_path = config['analysis_path']
cellranger_path = analysis_path + "/cellranger/"
scripts_dir = config['scripts_dir']+'/'
raw_fastqs = glob.glob(fastqs_path + "*.fastq.gz")
fastq_lanes = ["L001","L002","L003","L004"]
sample_name = config['sample_name']
cr_sample_name = sample_name[:-3] # e.g. MHELAVELA_S2 becomes MHELAVELA
analysis_prefix = config['analysis_prefix']
seq_prefix = config["sequencing_prefix"]

def rename_fastq(s_name):
    '''
        renames the merged fastqs according to the bcl2fastq naming convention
        Sample input name: MERGED_BSSE_QGF_123456_ZXVN2SHG5_1_QWEERTY_T_scD_250c_r1v1_0_SI-GA-H5_S1_L003_I1_001.fastq.gz
    '''
    split_name = s_name.split('_')
    new_name = '_'.join(split_name[6:7]+split_name[-4:])
    return new_name


rule all:
    input:
        merged_fastqs = "merge_files_done.txt",
        rename_fastqs = "rename_fastqs_done.txt",
        # tricked_fastqs = expand(fastqs_path+"/merged/tricked/" + sample_name + "_" + "{lane_no}" + "_R1_001.fastq.gz", lane_no = fastq_lanes),
        move_after_tricking_fastqs = "move_fastqs_to_tricked_done.txt",
        cellranger = "cellranger_done.txt",
        bins_genome = analysis_path + "/filtering/" + analysis_prefix + "__bins_genome.tsv",
        chr_stops = analysis_path + "/filtering/" + analysis_prefix + "__chr_stops.tsv",
        filtered_cnvs = analysis_path + "/filtering/" + analysis_prefix + "__filtered_cnvs.tsv",
        filtered_counts = analysis_path + "/filtering/" + analysis_prefix + "__filtered_counts.tsv",

        cluster_frequencies = analysis_path + "/clustering/" + analysis_prefix + "__cluster_frequencies.txt",
        clustering_score = analysis_path + "/clustering/" + analysis_prefix + "__clustering_score.txt",
        cluster_profile_overlapping = analysis_path + "/clustering/" + analysis_prefix + "__cluster_profile_overlapping.png",
        cluster_sizes = analysis_path + "/clustering/" + analysis_prefix + "__cluster_sizes.txt",
        clusters_phenograph_assignment = analysis_path + "/clustering/" + analysis_prefix + "__clusters_phenograph_assignment.tsv",
        clusters_phenograph_cn_profiles = analysis_path + "/clustering/" + analysis_prefix + "__clusters_phenograph_cn_profiles.tsv",
        clusters_phenograph_count_profiles = analysis_path + "/clustering/" + analysis_prefix + "__clusters_phenograph_count_profiles.tsv",
        cn_cluster = analysis_path + "/clustering/" + analysis_prefix + "__cn_cluster.h5",
        cn_gene_cluster = analysis_path + "/clustering/" + analysis_prefix + "__cn_gene_cluster.tsv",
        tsne_output = analysis_path + "/clustering/" + analysis_prefix + "__tsne_output.png",
        secondary_analysis = "secondary_analysis_done.txt",
        cluster_plots_list = analysis_path + "/clustering/" + analysis_prefix + "__cluster_profile_files.txt",
        heatmap_plots_list = analysis_path + "/clustering/" + analysis_prefix + "__cn_genes_clusters_files.txt",

        raw_files_list = fastqs_path + "/merged/tricked/" + seq_prefix + "__raw_files.txt",

        # copy cellranger outputs
        cr_alarms_summary = cellranger_path + "/renamed/" + analysis_prefix + "__alarms_summary.txt", 
        cr_cnv_data = cellranger_path + "/renamed/" + analysis_prefix + "__cnv_data.h5", 
        cr_summary = cellranger_path + "/renamed/" + analysis_prefix + "__summary.csv", 
        cr_web_summary = cellranger_path + "/renamed/" + analysis_prefix + "__web_summary.html"

    output:
        
    run:
        print("echo rule all")


rule merge_files:
    params:
        fastqs_path = fastqs_path,
	scripts_dir = scripts_dir
    input:
        raw_fastqs = expand('{sample}', sample=raw_fastqs)
    output:
        done = "merge_files_done.txt"
    shell:
        "sh {params.scripts_dir}/merge_10x_gzip_files.sh {params.fastqs_path}; \
	if [ -d {params.fastqs_path}/merged ] ; \
	then \
	    echo merged directory exists;\
	else \
	    mkdir {params.fastqs_path}/merged;\
	fi ; \
        mv {params.fastqs_path}/MERGED_BSSE* {params.fastqs_path}/merged;\
        chmod 755 {params.fastqs_path}/merged/*;\
	touch merge_files_done.txt"

rule rename_fastqs:
    input:
        rules.merge_files.output.done
    output:
        "rename_fastqs_done.txt"
    run:
        merged_fastqs_path = fastqs_path + "/merged/"
	print(merged_fastqs_path)
	fastqs_dir = merged_fastqs_path
	for filename in os.listdir(fastqs_dir):
    	    if filename.startswith("MERGED_BSSE") and filename.endswith('.gz'):
    	        print("old name: " + filename)
                print("new name: " + rename_fastq(filename))
                os.rename(fastqs_dir+filename, fastqs_dir+rename_fastq(filename))
        Path('rename_fastqs_done.txt').touch()

rule trick_fastqs:
    params:
        fastqs_path = fastqs_path,
        scripts_dir = scripts_dir,
        r1 = fastqs_path+"/merged/" + sample_name + "_" + "{lane_no}" + "_R1_001.fastq.gz",
        r2 = fastqs_path+"/merged/" + sample_name + "_" + "{lane_no}" + "_R2_001.fastq.gz",
        mem = config["tricking_fastqs"]["mem"],
        time = config["tricking_fastqs"]["time"] 
    input:
        rules.rename_fastqs.output
    output:
        fastqs_path+"/merged/tricked/" + sample_name + "_" + "{lane_no}" + "_R1_001.fastq.gz"
    shell:
        "\
        if [ -d {params.fastqs_path}/merged/tricked ] ; \
        then \
        echo tricked directory exists;\
        else \
        mkdir {params.fastqs_path}/merged/tricked;\
        fi ;\
        python {params.scripts_dir}/cellranger_dna_trick.py -r1 {params.r1}  -r2 {params.r2} -o {params.fastqs_path}/merged/tricked/"

rule move_fastqs:
    params:
        fastqs_path = fastqs_path
    input:
        tricked_fastqs = expand(fastqs_path+"/merged/tricked/" + sample_name + "_" + "{lane_no}" + "_R1_001.fastq.gz", lane_no = fastq_lanes)
    output:
        "move_fastqs_to_tricked_done.txt"
    shell:
        "mv {params.fastqs_path}/merged/*_R2_* {params.fastqs_path}/merged/tricked/; mv {params.fastqs_path}/merged/*_I1_* {params.fastqs_path}/merged/tricked/; chmod 755 {params.fastqs_path}/merged/tricked/*; touch move_fastqs_to_tricked_done.txt"

rule create_raw_files_list:
    params:
        fastqs_path = fastqs_path,
        seq_prefix = seq_prefix
    input:
        move_after_tricking_fastqs = "move_fastqs_to_tricked_done.txt"
    output:
        fastqs_path + "/merged/tricked/" + seq_prefix + "__raw_files.txt"
    shell:
        "cd {params.fastqs_path}/merged/tricked; ls > {params.seq_prefix}__raw_files.txt "

rule create_cluster_plots_list:
    params:
        analysis_prefix = analysis_prefix,
        analysis_path = analysis_path
    input:
        secondary_analysis_done = "secondary_analysis_done.txt"
    output:
        cluster_plots_list = analysis_path + "/clustering/" + analysis_prefix + "__cluster_profile_files.txt"
    shell:
        "cd {params.analysis_path}/clustering; ls | egrep '{params.analysis_prefix}__cluster_profile_..?\.png' > {params.analysis_prefix}__cluster_profile_files.txt"

rule create_heatmap_plots_list:
    params:
        analysis_prefix = analysis_prefix,
        analysis_path = analysis_path
    input:
        secondary_analysis_done = "secondary_analysis_done.txt"
    output:
        heatmap_plots_list = analysis_path + "/clustering/" + analysis_prefix + "__cn_genes_clusters_files.txt"
    shell:
        "cd {params.analysis_path}/clustering; ls | egrep '{params.analysis_prefix}__cn_genes_clusters_chr..?_heatmap\.png' > {params.analysis_prefix}__cn_genes_clusters_files.txt"

rule run_cellranger:
    params:
        fastqs_path = fastqs_path+'/merged/tricked',
        cr_sample_name = cr_sample_name,
        cellranger_path = cellranger_path,
        local_cores = config['cellranger_dna']['local_cores'],
        local_mem = config['cellranger_dna']['local_mem'],
        mem_per_core = config['cellranger_dna']['mem_per_core'],
        mem = config['cellranger_dna']['mem'],
        time = config['cellranger_dna']['time']
    input:
        moved_tricked_fastqs = expand(fastqs_path+"/merged/tricked/" + sample_name + "_" + "{lane_no}" + "_R1_001.fastq.gz", lane_no = fastq_lanes),
        move_after_tricking_fastqs = "move_fastqs_to_tricked_done.txt",
        reference_path = config['ref_genome_path']
    output:
        cnv_data = cellranger_path + cr_sample_name + "/outs/cnv_data.h5",
        cellranger_done = "cellranger_done.txt"
    shell:
        'if [ -d {params.cellranger_path}/run ] ; \
        then \
        echo cellranger directory exists;\
        else \
        mkdir {params.cellranger_path}/run;\
        fi ;\
         pushd {params.cellranger_path}/run; cellranger-dna cnv --reference={input.reference_path} --fastqs={params.fastqs_path}\
         --localmem={params.local_mem} --localcores={params.local_cores} --mempercore={params.mem_per_core}\
         --id={params.cr_sample_name} --sample={params.cr_sample_name}; ln -s "{params.cellranger_path}/run/{params.cr_sample_name}/outs/cnv_data.h5"\
         "{params.cellranger_path}/{params.cr_sample_name}/outs/cnv_data.h5"; popd; touch cellranger_done.txt'

rule copy_cellranger_outputs:
    params:
        cr_sample_name = cr_sample_name,
        cellranger_path = cellranger_path,
        analysis_prefix = analysis_prefix
    input:
        cellranger_done = "cellranger_done.txt"
    output:
        cellranger_path + "/renamed/" + analysis_prefix + "__alarms_summary.txt", 
        cellranger_path + "/renamed/" + analysis_prefix + "__cnv_data.h5", 
        cellranger_path + "/renamed/" + analysis_prefix + "__summary.csv", 
        cellranger_path + "/renamed/" + analysis_prefix + "__web_summary.html"
    shell:
        "cd {params.cellranger_path}; \
         ln -s '{params.cellranger_path}/run/{params.cr_sample_name}/outs/cnv_data.h5'\
             '{params.cellranger_path}/renamed/{params.analysis_prefix}__cnv_data.h5';\
         ln -s '{params.cellranger_path}/run/{params.cr_sample_name}/outs/alarms_summary.txt'\
             '{params.cellranger_path}/renamed/{params.analysis_prefix}__alarms_summary.txt';\
         ln -s '{params.cellranger_path}/run/{params.cr_sample_name}/outs/summary.csv'\
             '{params.cellranger_path}/renamed/{params.analysis_prefix}__summary.csv';\
         ln -s '{params.cellranger_path}/run/{params.cr_sample_name}/outs/web_summary.html'\
             '{params.cellranger_path}/renamed/{params.analysis_prefix}__web_summary.html';"

rule secondary_analysis:
    params:
        analysis_prefix = analysis_prefix,
        analysis_path = analysis_path,
        h5_path = config['secondary_analysis']['h5_path'],
        genes_path = config['secondary_analysis']['genes_path'],
        all_genes_path = config['secondary_analysis']['all_genes_path'],
        bins = config['secondary_analysis']['bins_to_remove'],
        script_dir = scripts_dir+"../pipeline/run_secondary_analysis.py",
        config_file = config['self']
    input:
        rules.run_cellranger.output.cnv_data
    output:
        bins_genome = analysis_path + "/filtering/" + analysis_prefix + "__bins_genome.tsv",
        chr_stops = analysis_path + "/filtering/" + analysis_prefix + "__chr_stops.tsv",
        filtered_cnvs = analysis_path + "/filtering/" + analysis_prefix + "__filtered_cnvs.tsv",
        filtered_counts = analysis_path + "/filtering/" + analysis_prefix + "__filtered_counts.tsv",

        cluster_frequencies = analysis_path + "/clustering/" + analysis_prefix + "__cluster_frequencies.txt",
        clustering_score = analysis_path + "/clustering/" + analysis_prefix + "__clustering_score.txt",
        cluster_profile_overlapping = analysis_path + "/clustering/" + analysis_prefix + "__cluster_profile_overlapping.png",
        cluster_sizes = analysis_path + "/clustering/" + analysis_prefix + "__cluster_sizes.txt",
        clusters_phenograph_assignment = analysis_path + "/clustering/" + analysis_prefix + "__clusters_phenograph_assignment.tsv",
        clusters_phenograph_cn_profiles = analysis_path + "/clustering/" + analysis_prefix + "__clusters_phenograph_cn_profiles.tsv",
        clusters_phenograph_count_profiles = analysis_path + "/clustering/" + analysis_prefix + "__clusters_phenograph_count_profiles.tsv",
        cn_cluster = analysis_path + "/clustering/" + analysis_prefix + "__cn_cluster.h5",
        cn_gene_cluster = analysis_path + "/clustering/" + analysis_prefix + "__cn_gene_cluster.tsv",
        tsne_output = analysis_path + "/clustering/" + analysis_prefix + "__tsne_output.png",
        done = "secondary_analysis_done.txt"
    shell:
        'python {params.script_dir} -c {params.config_file}; touch secondary_analysis_done.txt'

